source 'http://rubygems.org'

gem 'allure-rspec', '2.13.6.3'
gem 'debase'
gem 'deep_enumerable'
gem 'faker'
gem 'gmail'
gem 'httpclient'
gem 'os'
gem 'parallel_tests'
gem 'pry'
gem 'reportportal', git: 'https://github.com/reportportal/agent-ruby.git', branch: 'master'
gem 'require_all'
gem 'rest-client'
gem 'roo'
gem 'rspec'
gem 'rspec_junit_formatter'
gem 'rspec-retry'
gem 'ruby-debug-ide'
gem 'rubyXL'
gem 'Tarspect', git: 'https://github.com/credavenue/Tarspect.git', branch: 'master'

gem 'selenium-webdriver'
